Repository RhythmPahwa14/AlgoVisualizer, pull requests merged in 2025-08, with the labels that each got.

#17 Add back-to-top feature with navigation button
  package-lock.json
  src/App.js
  src/ScrollToTop.js
Labels: enhancement, good first issue, GSSoC'25, level-2

#21 add about and contact page and handle the problem of buttons ui
  package-lock.json
  package.json
  src/App.js
  src/components/Footer.js
  src/components/about.js
  src/components/contact.js
  src/styles/about.css
  src/styles/contact.css
  src/styles/footer.css
  src/styles/home.css
  src/styles/navbar.css
Labels: enhancement, GSSoC'25, level-2

#23 Added Export Visualization as GIF/Video Feature
  .env.production
  .vercelignore
  EXPORT_FEATURES.md
  README.md
  package-lock.json
  package.json
  public/_redirects
  public/index.html
  public/manifest.json
  public/robots.txt
  src/components/ExportControls.js
  src/components/ExportDemo.js
  src/components/SimpleExportControls.js
  src/hooks/useVisualizationExport.js
  src/pages/Home.js
  src/pages/Searching.js
  src/pages/Sorting.js
  src/styles/ExportControls.css
  src/styles/ExportDemo.css
  src/styles/home.css
  src/utils/loadHtml2Canvas.js
  src/utils/simpleExporter.js
  src/utils/visualizationExporter.js
  vercel.json
Labels: enhancement, GSSoC'25, level-2

#24 Privacy page and Terms of Service page
  src/App.js
  src/components/Footer.js
  src/components/Privacy.js
  src/components/terms.js
  src/styles/privacy.css
  src/styles/terms.css
Labels: documentation, GSSoC'25, level-2

#25 Text hover visibility issue fixed
  public/index.html
  src/styles/home.css
  src/styles/navbar.css
Labels: enhancement, GSSoC'25, level-2

#26 feat: Add comprehensive step-by-step code explanation system
  src/components/CodeExplanation.js
  src/pages/Searching.js
  src/pages/Sorting.js
  src/styles/codeExplanation.css
Labels: enhancement, GSSoC'25, level-2

#37 Fixed Button Layout and Alignment on Sorting & Searching Page
  DEPLOYMENT-FIXES.md
  src/components/SimpleExportControls.js
  src/pages/Searching.js
  src/pages/Sorting.js
  src/styles/App.css
  src/styles/Searching.css
Labels: enhancement, GSSoC'25, level-2

#57 Removed hover background from navbar links
  src/styles/navbar.css
Labels: GSSoC'25, level-2

#79 Fixed UI-Consistency
  src/styles/App.css
  src/styles/Contributors.css
  src/styles/ExportControls.css
  src/styles/ExportDemo.css
  src/styles/HomeContributors.css
  src/styles/Searching.css
  src/styles/Sorting.css
  src/styles/about.css
  src/styles/codeExplanation.css
  src/styles/components.css
  src/styles/contact.css
  src/styles/doubt.css
  src/styles/footer.css
  src/styles/global-dark-theme.css
  src/styles/home.css
  src/styles/navbar.css
  src/styles/pages.css
  src/styles/privacy.css
  src/styles/terms.css
Labels: GSSoC'25, level-2

#81 searching page UI fixed.
  src/pages/Searching.js
  src/styles/ExportControls.css
  src/styles/Searching.css
  src/styles/pages.css
Labels: GSSoC'25, level-2

#82 Removed default underline from cards on hover
  src/styles/App.css
  src/styles/home.css
  src/styles/navbar.css
Labels: GSSoC'25, level-2

#83 Fix Contributors Page Theme Inconsistency - Implement Complete Dark/Light Mode Support
  src/components/Contributors.js
  src/pages/Documentation.js
  src/styles/Contributors.css
  src/styles/navbar.css
Labels: GSSoC'25, level-2

#84 Fixed text overflow
  src/components/SimpleExportControls.js
  src/styles/components.css
  src/styles/home.css
Labels: GSSoC'25, level-2

#142 Fix: Remove duplicate Back to Top #135
  public/index.html
Labels: GSSoC'25, level-2

#147 Fix: center-align section with proper spacing and consistent layout
  src/styles/home.css
Labels: GSSoC'25, level-2

#138 implemented the data structures(Linked List, Stack, Queue, Binary Tree) page
  src/ThemeContext.js
  src/algorithms/binaryTree.js
  src/algorithms/linkedList.js
  src/algorithms/queue.js
  src/algorithms/stack.js
  src/components/CodeExplanation.js
  src/components/Contributors.js
  src/components/ExportControls.js
  src/components/SimpleExportControls.js
  src/pages/DataStructures.js
  src/pages/Documentation.js
  src/pages/Searching.js
  src/pages/Sorting.js
  src/searching/CodePanel.jsx
  src/styles/App.css
  src/styles/Contributors.css
  src/styles/pages.css
  src/utils/simpleExporter.js
Labels: GSSoC'25, level-2

#170 Updated the documentation page for light and dark theme #74
  src/pages/Documentation.js
Labels: documentation, GSSoC'25, level-2, Gssoc

#173 UI Issue: Icons Not Visible on Dark Theme #153
  src/styles/home.css
Labels: enhancement, good first issue, GSSoC'25, level-2, Gssoc

#191 Fixed : Enhancement of 'How to use Export Features ' section
  src/styles/ExportDemo.css
Labels: GSSoC'25, level-2

#202 Fix backgorund of quick cards , fix UI backtotopButton and add animation on number of export demo cards
  public/index.html
  src/ScrollToTop.js
  src/styles/ExportDemo.css
  src/styles/home.css
Labels: GSSoC'25, level-2

#203 Fixed the color issue in Sorting Page for light theme as mentioned
  src/pages/Sorting.js
  src/styles/Sorting.css
Labels: GSSoC'25, level-2

#208 Fix text Visibility in graph page
  src/styles/pages.css
Labels: GSSoC'25, level-2

#192 Added FAQ bot
  src/components/FaqBotService.js
  src/components/FaqChatbot.js
  src/pages/Documentation.js
  src/pages/Home.js
  src/styles/faq-chatbot.css
Labels: enhancement, GSSoC'25, level-3, Gssoc

#223 Update FAQ chatbot UI (color scheme, fixes & polish)
  src/components/FaqChatbot.jsx
  src/styles/faq-chatbot.css
Labels: GSSoC'25, level-2

#242 Add Vercel Analytics and update dependencies
  package-lock.json
  package.json
  src/App.jsx
  src/components/Contributors.jsx
  src/styles/Contributors.css
Labels: bug, help wanted

#241 Pr create automate message
  .github/workflows/issue-create-automate-message.yml
  .github/workflows/pr-create-automate-message.yml
Labels: enhancement, GSSoC'25, level-2, Gssoc

#247 Redesign Home page with dashboard layout and enhanced UI
  src/components/Sidebar.jsx
  src/pages/Home.jsx
  src/styles/home.css
Labels: enhancement

#259 fix overflowing
  src/pages/Settings.jsx
Labels: GSSoC'25, level-2

#255 Created CODE_OF_CONDUCT.md #254
  CODE_OF_CONDUCT.md
Labels: GSSoC'25, level-2

#257 fix the box of the documentation
  src/styles/Documentation.css
Labels: GSSoC'25, level-2

#268 Add label for search input
  src/pages/Documentation.jsx
Labels: GSSoC'25, level-2

#266 Improve input validation by changing error message to alert for invalid target number
  src/pages/Searching.jsx
Labels: GSSoC'25, level-2

#274 Improve Landing page
  src/styles/home.css
Labels: GSSoC'25, level-2

#272 Add GitHub issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
Labels: GSSoC'25, level-2
