Repository RhythmPahwa14/AlgoVisualizer, pull requests merged in 2025-09, with the labels that each got.

#303 Enhance ScrollToTop Component with Smooth UX & Accessibility
  index.html
  package-lock.json
  package.json
  src/ScrollToTop.jsx
  src/components/Doubt.jsx
  src/components/Footer.jsx
  src/main.jsx
  src/styles/App.css
  src/styles/doubt.css
  src/styles/footer.css
  vite.config.js
Labels: GSSoC'25, level-2

#296 Enhanced text visibility in Graph Page
  src/pages/Graph.jsx
Labels: GSSoC'25, level-1

#308 Add space between button and link
  src/styles/home.css
Labels: GSSoC'25, level-2

#304 Added custom input feature for sorting algorithms
  src/pages/Sorting.jsx
Labels: GSSoC'25, level-2

#313 ✨ Added TimSort and IntroSort algorithms with animations
  src/algorithms/IntroSort.js
  src/algorithms/algorithms.json
  src/algorithms/timSort.js
  src/components/CodeExplanation.jsx
  src/data/quizQuestions.json
  src/pages/DataStructures.jsx
  src/pages/Documentation.jsx
  src/pages/Sorting.jsx
Labels: GSSoC'25, level-2

#315 Fixed : Enhance Text Styling in 'Learning Paths' Section on Home Page
  src/pages/Home.jsx
  src/styles/home.css
Labels: GSSoC'25, level-2

#317 Fix: Center authentication forms & reposition auth buttons
  src/App.jsx
  src/index.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/styles/App.css
Labels: GSSoC'25, level-3

#323 Fix Text Contrast on Sorting Page in Light Mode for Better Accessibility
  src/pages/Sorting.jsx
  src/styles/Sorting.css
Labels: GSSoC'25, level-2

#324 UI fixes
  src/components/Contributors.jsx
  src/components/GraphVisualizer.jsx
  src/components/QuizManager.jsx
  src/components/QuizStart.jsx
  src/components/Sidebar.jsx
  src/components/SimpleExportControls.jsx
  src/pages/DataStructures.jsx
  src/pages/Documentation.jsx
  src/pages/Graph.jsx
  src/pages/Searching.jsx
  src/pages/Settings.jsx
  src/pages/Sorting.jsx
  src/styles/Contributors.css
  src/styles/Documentation.css
  src/styles/Graph.css
  src/styles/Searching.css
  src/styles/codeExplanation.css
  src/styles/doubt.css
  src/styles/footer.css
  src/styles/global-theme.css
  src/styles/home.css
Labels: GSSoC'25, level-2

#332 Melissa contri to graph
  package-lock.json
  src/App.jsx
  src/algorithms/algorithms.json
  src/components/GraphVisualizer.jsx
  src/components/Sidebar.jsx
  src/pages/Documentation.jsx
  src/pages/Graph.jsx
  src/pages/GraphBFS.jsx
  src/pages/GraphDFS.jsx
  src/pages/GraphDijkstra.jsx
  src/pages/Home.jsx
Labels: enhancement, GSSoC'25, level-3, Gssoc

#340 Implemented linked list operations (insert, search, traverse, reverse..)
  package-lock.json
  src/App.jsx
  src/algorithms/linkedListAlgorithms.js
  src/components/LinkedList/LinkedListNode.jsx
  src/components/LinkedList/LinkedListVisualizer.jsx
  src/components/pages/LinkedListPage.jsx
  src/pages/DataStructures.jsx
  src/styles/LinkedList.css
Labels: GSSoC'25, level-2

#351 Fix the button content overlaps
  src/styles/Sorting.css
Labels: GSSoC'25, level-2

#410 ternarySearch
  src/algorithms/algorithms.json
  src/algorithms/ternarySearch.js
  src/components/CodeExplanation.jsx
  src/pages/Searching.jsx
Labels: GSSoC'25, level-3

#412 Settings added
  src/pages/Settings.jsx
  src/styles/global-theme.css
Labels: GSSoC'25, level-3, Gssoc

#404 Fix navbar alignment
  src/components/about.css
  src/components/about.jsx
  src/styles/about.css
  src/styles/navbar-top.css
Labels: GSSoC'25, level-3

#403 fixed the about page theme
  src/components/about.css
  src/components/about.jsx
  src/styles/about.css
Labels: GSSoC'25, level-3

#402 Fix footer logo to match the header logo
  src/components/Footer.jsx
  src/styles/footer.css
Labels: GSSoC'25, level-3

#415 Redesigned the contributors page
  src/components/Contributors.jsx
  src/styles/Contributors.css
Labels: GSSoC'25, level-3

#434 Textvisible
  src/components/about.css
Labels: GSSoC'25, level-3

#426 Modularized code and build fixes-reimplemented missing 5 sorting functionality
  src/algorithms/IntroSort.js
  src/algorithms/bubbleSort.js
  src/algorithms/bucketSort.js
  src/algorithms/heapSort.js
  src/algorithms/index.js
  src/algorithms/insertionSort.js
  src/algorithms/introSort.js
  src/algorithms/mergeSort.js
  src/algorithms/quickSort.js
  src/algorithms/radixSort.js
  src/algorithms/runner.js
  src/algorithms/selectionSort.js
  src/algorithms/shellSort.js
  src/algorithms/timSort.js
  src/components/Sorting.jsx
  src/data/algorithmInfo.js
  src/data/pseudocode.js
  src/pages/DataStructures.jsx
  src/pages/Sorting.jsx
  src/utils/sortingHelpers.js
Labels: GSSoC'25, level-3

#445 Fix: Dark/Light Mode Support for ComplexityBox Component
  src/components/ComplexityBox.jsx
  src/components/complexityBox.css
Labels: GSSoC'25, level-3

#482 Algorithm comparison improvement
  src/components/AlgorithmComparison.jsx
  src/pages/Blog.jsx
  src/styles/blog.css
Labels: GSSoC'25, level-3

#480 Revamp Algorithm Comparison UI: mobile-friendly two cards with animat…
  src/components/AlgorithmComparison.jsx
Labels: GSSoC'25, level-3

#495 Patched quiz module and updated UI design slightly
  src/components/QuizStart.jsx
  src/styles/Quiz.css
Labels: GSSoC'25, level-3

#494 Resolve light/dark mode styling issue of Graph
  src/components/GraphComparison.jsx
  src/components/GraphVisualizer.jsx
Labels: GSSoC'25, level-3

#497 add jump search in documentation
  src/pages/DataStructures.jsx
  src/pages/Documentation.jsx
Labels: GSSoC'25, level-3

#498 add exponential search in documentation
  src/pages/DataStructures.jsx
  src/pages/Documentation.jsx
Labels: GSSoC'25, level-3

#530 fix the issue of visiblity of last navLink and mobile-menu navlink on hovering it is not visible
  src/components/Navbar.jsx
  src/styles/navbar-top.css
Labels: GSSoC'25, level-3

#529 Cycle sort implementation
  src/algorithms/algorithms.json
  src/algorithms/cycleSort.js
  src/components/AlgorithmComparison.jsx
  src/components/AlgorithmVisualizer.jsx
  src/components/Sorting.jsx
  src/pages/DataStructures.jsx
Labels: GSSoC'25, level-3

#511 Fix: Align Bubble Sort visualization side-by-side with controls (#462)
  src/components/Sorting.jsx
  src/styles/Sorting.css
Labels: GSSoC'25, level-3

#539 added_mobile_responsiveness_for_performancestatistics_in_sortingpage
  src/styles/Sorting.css
Labels: GSSoC'25, level-3

#520 Add Bubble Sort documentation page and route (#512)
  src/App.jsx
  src/pages/DataStructures.jsx
  src/pages/SortingDoc.jsx
  src/styles/SortingDoc.css
  ter
Labels: GSSoC'25, level-3

#545 documentation- improve getting started
  README.md
Labels: GSSoC'25, level-3

#549 fix: correct ternary search navigation and visualization
  src/App.jsx
  src/pages/DataStructures.jsx
  src/pages/Searching.jsx
Labels: GSSoC'25, level-3

#550 fix: improve Jump Search description and pseudocode clarity
  src/pages/DataStructures.jsx
  src/pages/Searching.jsx
Labels: GSSoC'25, level-3

#551 fix: correct Exponential Search navigation and details
  src/pages/DataStructures.jsx
  src/pages/Searching.jsx
Labels: GSSoC'25, level-3

#554 fix: add Cycle Sort algorithm with visualization, pseudocode, and re…
  src/algorithms/cycleSort.js
  src/data/algorithmInfo.js
  src/data/allCodes.js
  src/data/pseudocode.js
  src/pages/DataStructures.jsx
  src/pages/Searching.jsx
Labels: GSSoC'25, level-3

#552 fix: improve Exponential Search navigation, description, and pseudocode
  src/pages/DataStructures.jsx
  src/pages/Searching.jsx
Labels: GSSoC'25, level-3

#559 Improve Footer Alignment and Consistency Across All Pages
  src/components/Footer.jsx
  src/styles/footer.css
Labels: GSSoC'25, level-3

#564 fix:add space btw icon and the text
  src/pages/Home.jsx
  src/styles/home.css
Labels: GSSoC'25, level-3

#567 Fix/footer-inmobile
  src/components/Footer.jsx
  src/styles/footer.css
Labels: GSSoC'25, level-3

#569 code added in bfs javascript
  src/data/allCodes.js
  src/pages/GraphBFS.jsx
Labels: GSSoC'25, level-3

#563 fix the searching redirection and make page for overview of searching
  package-lock.json
  src/App.jsx
  src/components/Navbar.jsx
  src/pages/SearchingOverview.jsx
  src/styles/global-theme.css
Labels: GSSoC'25, level-3

#576 fixed/Back on Top Button
  BACK_TO_TOP_DOCUMENTATION.md
  src/ScrollToTop.jsx
  src/components/EnhancedScrollToTop.jsx
  src/styles/navigatetotop.css
Labels: GSSoC'25, level-3

#598 🎨 UI Improvement: Footer Redesign (#579)
  package-lock.json
  src/styles/footer.css
Labels: GSSoC'25, level-3

#600 Added Backtracking overview and complexity for all 5 algorithms
  src/App.jsx
  src/components/BacktrackingVisualizer.jsx
  src/components/Navbar.jsx
  src/components/Sidebar.jsx
  src/data/allCodes.js
  src/pages/BacktrackingOverview.jsx
  src/pages/BacktrackingPage.jsx
Labels: GSSoC'25, level-3

#609 fix the community - overview page
  src/pages/CommunityLanding.jsx
  src/styles/global-theme.css
Labels: GSSoC'25, level-3

#608 Added separate custom graph inputs for graph comparison
  src/components/GraphComparison.jsx
  src/pages/GraphBFS.jsx
  src/pages/GraphDFS.jsx
  src/pages/GraphDijkstra.jsx
Labels: GSSoC'25, level-3

#610 Add Greedy algorithm pages and visualizer
  src/App.jsx
  src/components/GreedyVisualizer.jsx
  src/components/Navbar.jsx
  src/data/allCodes.js
  src/pages/GreedyOverview.jsx
  src/pages/GreedyPage.jsx
Labels: GSSoC'25, level-3

#614 Add Tree algorithms visualizer and overview page
  src/App.jsx
  src/components/Navbar.jsx
  src/components/TreeVisualizer.jsx
  src/data/allCodes.js
  src/pages/TreeOverview.jsx
  src/pages/TreePage.jsx
Labels: GSSoC'25, level-3

#630 Fix: Footer "Contribute" link now redirects to GitHub contribute page
  src/components/Footer.jsx
Labels: GSSoC'25, level-3

#631 Fix: Footer "Algorithms" link redirects correctly to Data Structures page
  src/components/Footer.jsx
Labels: GSSoC'25, level-3

#657 feat: Add Animate on Scroll (AOS) for enhanced UI (#642)
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/components/Contributors.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Navbar.jsx
  src/components/Sorting.jsx
  src/components/about.jsx
  src/components/contact.jsx
  src/pages/BacktrackingOverview.jsx
  src/pages/BacktrackingPage.jsx
  src/pages/ContributorLeaderboard.jsx
  src/pages/DCOverview.jsx
  src/pages/DCPage.jsx
  src/pages/DPOverview.jsx
  src/pages/DPPage.jsx
  src/pages/DataStructures.jsx
  src/pages/Graph.jsx
  src/pages/GraphBFS.jsx
  src/pages/GraphDFS.jsx
  src/pages/HashingOverview.jsx
  src/pages/HashingPage.jsx
  src/pages/Home.jsx
  src/pages/Searching.jsx
Labels: GSSoC'25, level-3, GSSoC

#643 Refactor Searching Algorithms and Unify Visualization Architecture
  src/algorithms/binarySearch.js
  src/algorithms/index.js
  src/algorithms/linearSearch.js
  src/algorithms/runner.js
  src/components/AlgorithmVisualizer.jsx
  src/components/Sorting.jsx
  src/components/UnifiedStats.jsx
  src/components/UnifiedVisualizer.jsx
  src/docs/UNIFIED_ARCHITECTURE.md
  src/pages/Searching.jsx
  src/styles/UnifiedVisualizer.css
Labels: GSSoC'25, level-3, GSSoC

#649 Fixed the overlaping button on Contact us page
  src/ScrollToTop.jsx
  src/styles/faq-chatbot.css
Labels: GSSoC'25, level-2, GSSoC, Hacktoberfest

#646 Improve Mobile Navigation and Footer Visibility
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Sorting.jsx
  src/styles/footer.css
  src/styles/navbar.css
Labels: GSSoC'25, level-3, GSSoC

#647 add Stack visualization with operations and info panel
  src/App.jsx
  src/components/Navbar.jsx
  src/components/Stack/Stack.css
  src/components/Stack/Stack.jsx
Labels: GSSoC'25, level-3, GSSoC

#656 Add Floating Feedback Button
  src/App.jsx
  src/components/FeedbackWidget.jsx
  src/styles/Feedback.css
Labels: GSSoC'25, level-2, GSSoC, Hacktoberfest

#691 Added a warning and improved visibility of Start Quiz button
  src/components/QuizStart.jsx
  src/styles/Quiz.css
Labels: GSSoC'25, level-3

#672 feature - interactive BST Visualizer: Instant Inserts, Batch Input, and Arrow-Order Traversals (Mobile-First UI)
  src/App.jsx
  src/components/BinaryTree/BinaryTreeVisualizer.css
  src/components/BinaryTree/BinaryTreeVisualizer.jsx
  src/components/BinaryTree/utils/bst.js
  src/components/BinaryTree/utils/layout.js
  src/components/Navbar.jsx
Labels: GSSoC'25, level-3

#674 Add Branch & Bound pages
  src/App.jsx
  src/components/BranchBoundVisualizer.jsx
  src/components/Navbar.jsx
  src/data/allCodes.js
  src/pages/BacktrackingPage.jsx
  src/pages/BranchBoundOverview.jsx
  src/pages/BranchBoundPage.jsx
Labels: GSSoC'25, level-3

#677 fix(dp): correct Fibonacci bases and add step highlight; init AOS once (fixes #650)
  src/components/DPVisualizer.jsx
  src/pages/DPPage.jsx
  src/styles/global-theme.css
Labels: GSSoC'25, level-2, GSSoC

#686 Fix: Improve Footer Responsiveness and Styling Consistency
  src/components/Footer.jsx
  src/styles/footer.css
Labels: GSSoC'25, level-2, GSSoC

#683 Navbar correction UI improvement
  src/styles/navbar.css
Labels: GSSoC'25, level-2, GSSoC

#676 Add Game Search visualizer and overview pages with routes and navbar …
  src/App.jsx
  src/components/GameSearchVisualizer.jsx
  src/components/Navbar.jsx
  src/data/allCodes.js
  src/pages/GameSearchOverview.jsx
  src/pages/GameSearchPage.jsx
Labels: GSSoC'25, level-3, GSSoC

#711 Fix: Improve Navigation Consistency and Structure Across Header and Navbar Components
  src/components/Header.jsx
  src/components/Navbar.jsx
  src/docs/NAVIGATION_STRUCTURE.md
  src/pages/DPPage.jsx
  src/utils/navigation.js
Labels: GSSoC'25, level-3

#712 Add documentation for 9 sorting algorithms to improve learning experience
  src/pages/SortingDoc.jsx
  src/styles/SortingDoc.css
Labels: GSSoC'25, level-2

#697 Add Code Editor Feature
  package-lock.json
  package.json
  src/App.jsx
  src/components/Navbar.jsx
  src/pages/CodeEditor.jsx
  src/pages/DPPage.jsx
Labels: GSSoC'25, level-3, GSSoC

#714 Enable Stack, Queue, and Binary Tree Visualizers with Routes
  src/pages/DataStructures.jsx
Labels: GSSoC'25, level-2, GSSoC

#690 Fix: Improve Footer Layout and Responsiveness for Better User Experience
  src/components/Footer.jsx
  src/styles/footer.css
Labels: GSSoC'25, level-2, GSSoC

#729 Correct toggle functionality
  src/components/terms.jsx
  src/styles/terms.css
Labels: GSSoC'25, level-3, GSSoC

#735 Added Landing page for Contribute
  src/App.jsx
  src/components/Contribute.jsx
  src/components/Footer.jsx
  src/styles/Contribute.css
  src/styles/theme.css
Labels: GSSoC'25, level-3, GSSoC

#746 fixed navbar #703
  src/App.jsx
  src/components/Navbar.jsx
  src/styles/navbar.css
  src/utils/navigation.js
Labels: GSSoC'25, level-3, GSSoC

#771 fixes#764 [feat] Feature/add tailwing library
  BACK_TO_TOP_DOCUMENTATION.md
  package-lock.json
  package.json
  src/TAILWIND_DOCS.md
  src/main.css
  src/main.jsx
  vite.config.js
Labels: GSSoC'25, level-3, GSSoC

#774 Resources correction
  src/styles/home.css
Labels: GSSoC'25, level-2

#782 aAded cycle detection topic in graph playlist
  package-lock.json
  package.json
  src/App.jsx
  src/components/DFSCycleVisualizer.jsx
  src/data/allCodes.js
  src/pages/GraphCycleDetection.jsx
  src/styles/global-theme.css
  src/utils/navigation.js
Labels: GSSoC'25, level-3

#820 fix: resolve issue #754 by correcting Binary Tree route and slug handling
  package-lock.json
  package.json
  src/App.jsx
  src/pages/DataStructures.jsx
Labels: GSSoC'25, level-2

#810 Fix: Inconsistent Branch & Bound Visualizer Implementation and UI/UX …
  src/components/GraphVisualizer.jsx
Labels: GSSoC'25, level-3, GSSoC

#824 Fix: Improve Theme Toggle Component Structure
  src/components/ThemeToggle.jsx
Labels: GSSoC'25, level-3, Hacktoberfest

#817 Fix Blog Cards Alignment and Styling
  src/pages/Blog.jsx
Labels: GSSoC'25, level-2, GSSoC, Hacktoberfest

#825 fix: improve TreeVisualizer layout and styling for traversal steps
  src/components/TreeVisualizer.jsx
  src/styles/TreeVisualizer.css
Labels: GSSoC'25, level-2, Hacktoberfest
