Repository RhythmPahwa14/AlgoVisualizer, pull requests merged in 2025-10, with the labels that each got.

#837 Fix: Enhance Quiz Manager Component Organization
  src/components/QuizManager.jsx
Labels: GSSoC'25, level-2

#840 Fix: Improve Graph Visualizer Component Structure
  src/components/GraphVisualizer.jsx
Labels: GSSoC'25, level-2

#835 Fix: Optimize Footer Component Structure and Maintainability
  src/components/Footer.jsx
Labels: GSSoC'25, level-2, Hacktoberfest

#849 Added feature cards Data Structures, Graph Algorithms, Paradigms and …
  src/components/about.jsx
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#861 fixes#812 [Bug] changed the position of overlayed div in visializatoin in binary sear…
  src/pages/Searching.jsx
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#863 fixes#813 [Bug] now shows number when greater than 25 size
  src/pages/Searching.jsx
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#883 Moved visualization to bottom from right to see sorting for large array
  src/components/Sorting.jsx
  src/styles/LinkedList.css
Labels: GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#881 Ds docs
  src/App.jsx
  src/components/Footer.jsx
  src/pages/DSDocumentation.jsx
  src/pages/Documentation.jsx
Labels: GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#892 fixes error which causes application to see blank screen
  src/components/Sorting.jsx
  src/pages/Documentation.jsx
Labels: bug, GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#899 changed null to default fa icon
  src/components/Footer.jsx
  src/components/ThemeToggle.jsx
Labels: bug, help wanted, GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#900 Duplicate keys and miscategorized algorithms in algorithmDatabase
  src/pages/Documentation.jsx
Labels: bug, GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#914 Add Paradigm & Other Topics Sections in Quiz Module
  src/components/QuizManager.jsx
  src/data/quizQuestions.json
Labels: enhancement, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#917 feat: improve Matrix Chain visualization with focus highlight and persistent result box
  src/components/DPVisualizer.jsx
  src/styles/global-theme.css
Labels: bug, GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#916 enhancement: added proper alignment to the description of the algorithm cards in the documentation page
  package-lock.json
  package.json
  src/styles/global-theme.css
Labels: enhancement, GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#915 fix: correct LCS visualization and add focus highlight styling
  src/components/DPVisualizer.jsx
  src/styles/global-theme.css
Labels: bug, GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#920 Align & polish three-column layout, synchronise animations, and improve mobile behaviour
  src/pages/Home.jsx
  src/styles/global-theme.css
  src/styles/home.css
Labels: bug, enhancement, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#922 feat: Extend quiz question bank with Branch & Bound and Game Search algorithms
  package.json
  src/components/QuizStart.jsx
  src/data/quizQuestions.json
  vite.config.js
Labels: GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#938 fixed clear documentation and contributor guide
  CONTRIBUTING.md
  README.md
Labels: documentation, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#927 Fix: Footer icons and Color schema working in navbar and footer
  src/components/Footer.jsx
  src/styles/feedback.css
  src/styles/footer-improved.css
  src/styles/navbar-top.css
  src/styles/settings.css
Labels: bug, good first issue, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#931 Custominput/custominput
  README.md
  USER_INPUT_DOCUMENTATION.md
  public/sample-data/README.md
  public/sample-data/sample-array.csv
  public/sample-data/sample-array.json
  public/sample-data/sample-graph.json
  public/sample-data/sample-tree.json
  src/components/InputPanel.jsx
  src/components/Sorting.jsx
  src/data/sampleData.js
  src/pages/GraphBFS.jsx
  src/pages/GraphDFS.jsx
  src/pages/GraphDijkstra.jsx
  src/pages/Searching.jsx
  src/styles/InputPanel.css
Labels: enhancement, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#936 Updated the questions of Paradigm and other quiz topics
  src/data/quizQuestions.json
Labels: documentation, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#951 User dropdown improvements
  src/components/UserDropdown.jsx
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#957 Login Implementation
  src/pages/Login.jsx
  src/styles/Login.css
Labels: enhancement, GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#967 Signup functionality
  src/App.jsx
  src/pages/Signup.jsx
  src/styles/Signup.css
Labels: enhancement, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#972 UI change userDropdown
  src/components/UserDropdown.jsx
  src/styles/UserDropdown.css
Labels: bug, GSSoC'25, level-2, Hacktoberfest, hacktoberfest-accepted

#926 Add Interactive Code Examples to Notes Pages for Java
  package.json
  src/App.jsx
  src/components/CodeRunnerJava.jsx
  src/pages/Notes/Java/JavaBasics.jsx
Labels: enhancement, GSSoC'25, level-2, Hacktoberfest, hacktoberfest-accepted

#975 Add Java OOP Concepts Page to Learning Platform
  src/App.jsx
  src/pages/JavaOOPS.jsx
Labels: enhancement, GSSoC'25, level-2, Hacktoberfest, hacktoberfest-accepted

#983 resolves nav bar misalignment
  package-lock.json
Labels: enhancement, GSSoC'25, level-2, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1018 Add Real-time Notifications and Algorithm Subscription System
  src/App.jsx
  src/components/NotificationWidget.jsx
  src/components/SubscribeButton.jsx
  src/contexts/NotificationsContext.jsx
  src/pages/DPPage.jsx
  src/pages/Sorting.jsx
Labels: enhancement, GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1028 Enhance Contribute page with icons and tech stack
  package-lock.json
  src/components/Contribute.jsx
Labels: GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#1022 fix: position notification panel below navbar
  src/components/NotificationWidget.jsx
Labels: bug, GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#1030 Add new Java fundamentals topics to menu
  src/pages/Notes/Java/Fundamentals.jsx
Labels: GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#1033 fix: blue screen issue
  src/components/AlgorithmVisualizer.jsx
Labels: GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#1058 searching_hard_level_questions_added
  src/data/quizQuestions.json
Labels: enhancement, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1061 Searching_medium_level_questions_added
  src/data/quizQuestions.json
Labels: enhancement, GSSoC'25, level-3, hacktoberfest-accepted

#1062 Move social media icons to the left section under tech stack badges
  src/components/Footer.jsx
  src/styles/footer.css
Labels: enhancement, GSSoC'25, level-2, hacktoberfest-accepted

#1063 Improved Toggle button
  src/components/ThemeToggle.jsx
Labels: GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1064 add the start script in package.json
  package.json
Labels: bug, GSSoC'25, level-2, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1034 🎨 Scroll Utilities CSS Enhancement
  src/styles/navigatetotop.css
Labels: GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1038 🎨 Mega Menu CSS Enhancement
  src/styles/navbar.css
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#1040 fix: make notification widget responsive for mobile devices
  src/components/NotificationWidget.jsx
Labels: hacktoberfest-accepted

#1017 Add Global Context for Selected Algorithm and Difficulty Level
  src/App.jsx
  src/components/ComplexityBox.jsx
  src/contexts/AlgorithmContext.jsx
Labels: Conflict

#1012 Javascript notes
  package-lock.json
  src/App.jsx
  src/components/Navbar.jsx
  src/pages/Notes/Cpp/VariablesAndDataTypes.jsx
  src/pages/Notes/Javascript/Fundamentals.jsx
  src/pages/Notes/Javascript/VariableAndDataTypes.jsx
Labels: GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted, Conflict

#1093 Java fundamentals.jsx modularization and content addition
  package-lock.json
  src/pages/Notes/Java/Fundamentals.jsx
  src/pages/Notes/Java/sections/ArraysSection.jsx
  src/pages/Notes/Java/sections/ClassesSection.jsx
  src/pages/Notes/Java/sections/CollectionsSection.jsx
  src/pages/Notes/Java/sections/ConstructorsSection.jsx
  src/pages/Notes/Java/sections/ControlFlowSection.jsx
  src/pages/Notes/Java/sections/DataTypesSection.jsx
  src/pages/Notes/Java/sections/EncapsulationSection.jsx
  src/pages/Notes/Java/sections/ExceptionsSection.jsx
  src/pages/Notes/Java/sections/FileHandlingSection.jsx
  src/pages/Notes/Java/sections/InheritanceSection.jsx
  src/pages/Notes/Java/sections/InterfacesSection.jsx
  src/pages/Notes/Java/sections/IntroSection.jsx
  src/pages/Notes/Java/sections/LoopsSection.jsx
  src/pages/Notes/Java/sections/MethodsSection.jsx
  src/pages/Notes/Java/sections/OOPSection.jsx
  src/pages/Notes/Java/sections/OperatorsSection.jsx
  src/pages/Notes/Java/sections/PackagesSection.jsx
  src/pages/Notes/Java/sections/PolymorphismSection.jsx
  src/pages/Notes/Java/sections/SetupSection.jsx
  src/pages/Notes/Java/sections/StringsSection.jsx
  src/pages/Notes/Java/sections/SyntaxSection.jsx
  src/pages/Notes/Java/sections/VariablesSection.jsx
Labels: bug, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1072 Applied strict password setting while creating account
  package-lock.json
  package.json
  src/main.css
  src/main.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#1108 Fix/critical api key security issue
  .env.example
  SECURITY.md
  src/components/CodeRunnerJava.jsx
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#1075 📊 Queue Module Enhancement
  src/algorithms/queue.js
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#1077 📚 Stack Module Enhancement
  src/algorithms/stack.js
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#1096 Add Gamification & Progress Tracker for Learners
  src/App.jsx
  src/components/LearnerLeaderboard.jsx
  src/components/ProgressTracker.jsx
  src/components/WeeklyChallenge.jsx
Labels: enhancement, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1101 Improved the documentation(/data-structures) section/page
  src/pages/DataStructures.jsx
Labels: enhancement, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1094 Add Interactive Algorithm Playground
  src/App.jsx
  src/pages/Playground.jsx
Labels: enhancement, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1083 🎨 Visualization Export Module Enhancement
  src/utils/simpleExporter.js
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#1078 🎨 Binary Tree Visualizer CSS Enhancement
  src/components/BinaryTree/BinaryTreeVisualizer.css
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#1089 Google Auth added
  index.html
  src/App.jsx
  src/contexts/GoogleAuthContext.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
  src/styles/Login.css
  src/styles/Signup.css
Labels: GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#1082 🎯 Linked List Visualizer Component Enhancement
  src/components/LinkedList/LinkedListVisualizer.jsx
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#1092 Add new C++ topics section
  src/pages/Notes/Cpp/Fundamentals.jsx
Labels: enhancement, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1118 Fix paragraph text visibility in Light Mode
  src/pages/Notes/C/Fundamentals.jsx
  src/pages/Notes/Cpp/Fundamentals.jsx
  src/pages/Notes/Java/Fundamentals.jsx
  src/pages/Notes/Python/Fundamentals.jsx
Labels: bug, GSSoC'25, level-2, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1124 Implement Strand Sort Algorithm
  package-lock.json
  src/algorithms/strandSort.js
  src/components/CodeExplanation.jsx
  src/components/Sorting.jsx
  src/data/algorithmInfo.js
Labels: enhancement, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1127 Fix footer links for Algorithm and Data Structure
  src/utils/footerData.js
Labels: bug, GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1129 Fix: Remove blue underline on 'Start Learning' and 'Take a Quiz' butt…
  src/styles/home.css
Labels: GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1131 Added Rabin–Karp String Matching Visualizer
  src/App.jsx
  src/components/RabinKarpVisualizer.jsx
  src/pages/StringRabinKarpPage.jsx
  src/styles/global-theme.css
  src/utils/navigation.js
Labels: enhancement, GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#1130 Pythonmodularized
  package-lock.json
  src/pages/Notes/Python/Python/Fundamentals.jsx
  src/pages/Notes/Python/Python/PythonBasics.jsx
  src/pages/Notes/Python/Python/VariablesAndDataTypes.jsx
  src/pages/Notes/Python/Python/sections/ControlFlowSection.jsx
  src/pages/Notes/Python/Python/sections/DSASection.jsx
  src/pages/Notes/Python/Python/sections/DataTypesSection.jsx
  src/pages/Notes/Python/Python/sections/ExamplesSection.jsx
  src/pages/Notes/Python/Python/sections/FilesSection.jsx
  src/pages/Notes/Python/Python/sections/FunctionsSection.jsx
  src/pages/Notes/Python/Python/sections/IntroSection.jsx
  src/pages/Notes/Python/Python/sections/IteratorsSection.jsx
  src/pages/Notes/Python/Python/sections/ModulesSection.jsx
  src/pages/Notes/Python/Python/sections/NumpySection.jsx
  src/pages/Notes/Python/Python/sections/OOPSection.jsx
  src/pages/Notes/Python/Python/sections/OperatorsSection.jsx
  src/pages/Notes/Python/Python/sections/SetupSection.jsx
  src/pages/Notes/Python/Python/sections/SyntaxSection.jsx
  src/pages/Notes/Python/Python/sections/VariablesSection.jsx
Labels: GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1136 fix: make search & filter section theme-aware using useTheme
  package-lock.json
  src/pages/DataStructures.jsx
Labels: bug, GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1192 Contribute Page gap
  src/components/Contribute.jsx
  src/components/about.css
  src/components/about.jsx
  src/styles/home.css
Labels: GSSoC'25, level-1, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1151 javascript notes #952
  src/App.jsx
  src/components/Navbar.jsx
  src/pages/Notes/JavaScript/Fundamentals.jsx
  src/pages/Notes/JavaScript/VariablesAndDataTypes.jsx
Labels: GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#1152 fix: Apply consistent gradient styling to all section headings (#675)
  src/styles/Sorting.css
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#1159 fix: community page CSS issues
  src/pages/CommunityLanding.jsx
Labels: bug, GSSoC'25, level-1, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1168 Add Git & GitHub Basics section to Learner Page
  src/App.jsx
  src/pages/GitLearning.jsx
Labels: enhancement, GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1183 Add Debug Logging and Performance Monitoring to Visualization Export Hook
  src/hooks/useVisualizationExport.js
Labels: GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1185 Blog Page - Accessibility, Performance Monitoring, and Debugging Overhaul
  src/pages/Blog.jsx
Labels: GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1186 Branch and Bound Overview - Accessibility, Performance, and Debugging Overhaul
  src/pages/BranchBoundOverview.jsx
Labels: GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1188 🔒 FEATURE/ENHANCEMENT: Code Editor - Accessibility, Security, and Debugging Overhaul
  src/pages/CodeEditor.jsx
Labels: GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1190 ✨ ENHANCEMENT: Contributor Board - Accessibility, Performance, and Dashboard Overhaul
  src/pages/ContributorBoard.jsx
Labels: GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1194 Update quizQuestions.json with 30+ question of new algo
  src/data/quizQuestions.json
Labels: documentation, GSSoC'25, level-3, GSSoC, hacktoberfest-accepted

#1197 Add theme-adaptive dark/light mode to Home Recent Updates section
  package-lock.json
  src/pages/Home.jsx
Labels: bug, GSSoC'25, level-2, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1198 Enhance Feedback Form
  src/components/Doubt.jsx
  src/styles/doubt.css
Labels: GSSoC'25, level-2, GSSoC, hacktoberfest-accepted

#1199 Improve JavaScript fundamentals with modular structure
  src/pages/Notes/JavaScript/Fundamentals.jsx
  src/pages/Notes/JavaScript/sections/DataTypesSection.jsx
  src/pages/Notes/JavaScript/sections/FunctionsSection.jsx
  src/pages/Notes/JavaScript/sections/IntroSection.jsx
  src/pages/Notes/JavaScript/sections/ObjectsSection.jsx
  src/pages/Notes/NotesPage.jsx
Labels: enhancement, GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted

#1200 Add copy to clipboard functionality and random array generator to Cod…
  src/components/CodeExplanation.jsx
  src/components/InputPanel.jsx
  src/styles/codeExplanation.css
Labels: hacktoberfest-accepted

#1203 Add “Forgot Password / Reset Password” Functionality
  Backend/src/routes/auth.js
  Backend/src/routes/authController.js
  Backend/src/routes/emailService.js
  src/pages/ForgotPassword.jsx
  src/pages/Login.jsx
  src/pages/ResetPassword.jsx
  src/routes/AppRoutes.jsx
  src/services/authService.js
Labels: GSSoC'25, level-3, GSSoC, Hacktoberfest, hacktoberfest-accepted
